version: "3.7"

services:
  mongodb:
    image: mongo
    ports:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: LocalUser
      MONGO_INITDB_ROOT_PASSWORD: LocalPass1
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/admin --quiet
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - mongo_storage:/data/db

  mongodb-ui:
    image: mongo-express
    ports:
      - 5001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: LocalUser
      ME_CONFIG_MONGODB_ADMINPASSWORD: LocalPass1
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      mongodb:
        condition: service_healthy

  indexer:
    build: ../indexer
    environment:
      KAFKA_BROKER_URL: broker:9092
      DETECTIONS_TOPIC: intellisite.detections
      ALERTS_TOPIC: intellisite.alerts
      SUSPICIOUS_VEHICLE: SUV
      MONGO_USERNAME: LocalUser
      MONGO_PASSWORD: LocalPass1
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: indexer

networks:
  default:
   external:
     name: intellisite

volumes:
  mongo_storage:
