version: "3.7"

services:
  api:
    container_name: docker-api
    build:
      context: ../api
    ports:
      - 8080:8080
    volumes:
      - ../api:/api/
    environment:
      KAFKA_BROKER_URL: broker:9092
      ALERTS_TOPIC: intellisite.alerts
      MONGO_USERNAME: LocalUser
      MONGO_PASSWORD: LocalPass1
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: indexer
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

networks:
  default:
   external:
     name: intellisite
